name: Issue creation

on:
  issues:
    types: [ opened ]
  pull_request:
    branches: [ master ]

jobs:
    interaction:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/first-interaction@v1
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            issue-message: |
              Takyou for posting an issue

              Please make sure that there is no other related issue
            pr-message: |
                Thank you for your contribution

                Please folow the CONTRIBUTION.md rules
